export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const GET_FILTERED_PRODUCTS = "GET_FILTERED_PRODUCTS";
export const GET_PRODUCTS = "GET_PRODUCTS";

export const GET_CURRENCIES = "GET_CURRENCIES";
export const SELECTED_CURRENCY = "SELECTED_CURRENCY";

export const GET_CART_PRODUCTS = "GET_CART_PRODUCTS";
export const REMOVE_ITEM = "REMOVE_ITEM";
